CREATE DATABASE Sales_Store_DB;
USE Sales_Store_DB;

# Dataset Table Creation 
CREATE TABLE Sales_Staging (
    transaction_id VARCHAR(20),
    customer_id VARCHAR(20),
    customer_name VARCHAR(100),
    customer_age INT,
    gender VARCHAR(10),
    product_id VARCHAR(20),
    product_name VARCHAR(150),
    product_category VARCHAR(100),
    quantity INT,
    price DECIMAL(10,2),
    payment_mode VARCHAR(50),
    purchase_date VARCHAR(30),      
    time_of_purchase VARCHAR(30),  
    status VARCHAR(30)
);



# Customer Table
CREATE TABLE Customers (
    customer_id VARCHAR(20) PRIMARY KEY,
    customer_name VARCHAR(100),
    customer_age INT,
    gender VARCHAR(10)
);

# Product Table 
CREATE TABLE Products (
    product_id VARCHAR(20) PRIMARY KEY,
    product_name VARCHAR(150),
    product_category VARCHAR(100),
    price DECIMAL(10,2)
);

# Transactions Table
CREATE TABLE Transactions (
    transaction_id VARCHAR(20) PRIMARY KEY,
    customer_id VARCHAR(20),
    purchase_date DATE,
    time_of_purchase TIME,
    status VARCHAR(30)
);

# Payment Table
CREATE TABLE Payments (
    transaction_id VARCHAR(20) PRIMARY KEY,
    payment_mode VARCHAR(50)
);

# Transaction_Items Table
CREATE TABLE Transaction_Items (
    transaction_id VARCHAR(20),
    product_id VARCHAR(20),
    quantity INT,
    price DECIMAL(10,2),
    PRIMARY KEY (transaction_id, product_id)
);

INSERT IGNORE INTO Customers
SELECT customer_id, customer_name, customer_age, gender
FROM Sales_Staging;

INSERT IGNORE INTO Products
SELECT  product_id, product_name, product_category, price
FROM Sales_Staging;

INSERT IGNORE INTO Transactions
SELECT
    transaction_id,
    customer_id,
    STR_TO_DATE(purchase_date, '%d-%m-%Y'),
    time_of_purchase,
    status
FROM Sales_Staging;

INSERT IGNORE INTO Payments
SELECT transaction_id, payment_mode
FROM Sales_Staging;

INSERT IGNORE Transaction_Items
SELECT
    transaction_id,
    product_id,
    quantity,
    price
FROM Sales_Staging;

SELECT COUNT(*) FROM Customers;
SELECT COUNT(*) FROM Products;
SELECT COUNT(*) FROM Transactions;
SELECT COUNT(*) FROM Payments;
SELECT COUNT(*) FROM Transaction_Items;


# Add Foreign Keys (ER Relationships)
ALTER TABLE Transactions
ADD CONSTRAINT fk_transactions_customers
FOREIGN KEY (customer_id) REFERENCES Customers(customer_id);

ALTER TABLE Payments
ADD CONSTRAINT fk_payments_transactions
FOREIGN KEY (transaction_id) REFERENCES Transactions(transaction_id);

ALTER TABLE Transaction_Items
ADD CONSTRAINT fk_items_transactions
FOREIGN KEY (transaction_id) REFERENCES Transactions(transaction_id);

ALTER TABLE Transaction_Items
ADD CONSTRAINT fk_items_products
FOREIGN KEY (product_id) REFERENCES Products(product_id);

# Key Analysis 

# 1. What is the total sales revenue generated by the store?
SELECT 
    SUM(quantity * price) AS total_revenue
FROM
    transaction_items;

# 2. Which products generate the highest sales revenue?
SELECT 
    p.product_name AS Products,
    SUM(ti.quantity * ti.price) AS Revenue
FROM
    transaction_items ti
        JOIN
    products p ON ti.product_id = p.product_id
GROUP BY Products
ORDER BY revenue DESC;

# 3. Which product categories are selling the most?
SELECT 
    p.product_category, SUM(ti.quantity * ti.price) AS Revenue
FROM
    transaction_items ti
        JOIN
    products p ON ti.product_id = p.product_id
GROUP BY p.product_category
ORDER BY Revenue DESC;

# 4. Which customers purchase the most frequently?
SELECT 
    c.customer_name AS Customers,
    COUNT(ti.transaction_id) AS Total_Purchases
FROM
    transactions ti
        INNER JOIN
    customers c ON c.customer_id = ti.customer_id
GROUP BY Customers
ORDER BY Total_Purchases DESC;

# 5. What is the average quantity sold per transaction?
SELECT 
    AVG(quantity) AS avg_quantity_per_transaction
FROM
    transaction_items;
    
# 6. Which payment mode is most preferred by customers?
SELECT 
    payment_mode, COUNT(*) AS Most_preferred_by_Customers
FROM
    payments
GROUP BY payment_mode
ORDER BY Most_preferred_by_Customers DESC;

# 7. How many transactions are completed, cancelled, or pending?
SELECT 
    status, COUNT(*) total_transactions
FROM
    transactions
GROUP BY status;

# 8. Which time of day has the highest number of purchases?
SELECT 
    HOUR(time_of_purchase) AS purchase_hour,
    COUNT(*) total_orders
FROM
    transactions
GROUP BY purchase_hour
ORDER BY total_orders DESC;

# 9. Which age group of customers purchases the most products?
SELECT 
    CASE
        WHEN customer_age < 25 THEN 'Below 25'
        WHEN customer_age BETWEEN 25 AND 40 THEN '25–40'
        ELSE 'Above 40'
    END AS age_group,
    SUM(ti.quantity * ti.price) AS total_sales
FROM
    customers c
        JOIN
    transactions t ON c.customer_id = t.customer_id
        JOIN
    transaction_items ti ON t.transaction_id = ti.transaction_id
GROUP BY age_group;

# 10. Which age group of customers purchases the most products?
SELECT 
    p.product_name, SUM(ti.quantity * ti.price) AS revenue
FROM
    transaction_items ti
        JOIN
    products p ON ti.product_id = p.product_id
GROUP BY p.product_name
ORDER BY revenue ASC;

# 11. Which customers generate the highest revenue?
SELECT 
    c.customer_name, SUM(ti.quantity * ti.price) AS total_spent
FROM
    customers c
        JOIN
    transactions t ON c.customer_id = t.customer_id
        JOIN
    transaction_items ti ON t.transaction_id = ti.transaction_id
GROUP BY c.customer_name
ORDER BY total_spent DESC;

# 12. What is the overall sales trend by date?
SELECT 
    t.purchase_date,
    SUM(ti.quantity * ti.price) AS daily_revenue
FROM
    transactions t
        JOIN
    transaction_items ti ON t.transaction_id = ti.transaction_id
GROUP BY t.purchase_date
ORDER BY t.purchase_date;

# 13. Which products have the highest repeat purchases?
SELECT 
    p.product_name,
    COUNT(ti.transaction_id) AS repeat_purchases
FROM
    transaction_items ti
        JOIN
    products p ON ti.product_id = p.product_id
GROUP BY p.product_name
ORDER BY repeat_purchases DESC;

# 14. Which payment modes are associated with higher order values?
SELECT 
    p.payment_mode,
    AVG(ti.quantity * ti.price) AS avg_order_value
FROM
    payments p
        JOIN
    transaction_items ti ON p.transaction_id = ti.transaction_id
GROUP BY p.payment_mode
ORDER BY avg_order_value DESC;

# 15. Which days have the highest and lowest sales volume?
SELECT 
    t.purchase_date, SUM(ti.quantity) AS total_quantity_sold
FROM
    transactions t
        JOIN
    transaction_items ti ON t.transaction_id = ti.transaction_id
GROUP BY t.purchase_date
ORDER BY total_quantity_sold DESC;

# 16. Which products have declining sales trends over time?
SELECT 
    p.product_name,
    t.purchase_date,
    SUM(ti.quantity) AS daily_quantity
FROM
    transaction_items ti
        JOIN
    transactions t ON ti.transaction_id = t.transaction_id
        JOIN
    products p ON ti.product_id = p.product_id
GROUP BY p.product_name , t.purchase_date
ORDER BY p.product_name , t.purchase_date;


